#!/usr/bin/python

import os
import re
import time
import random
import platform
import shutil
from ConfigParser import ConfigParser

import RSSparse
import PAGEparse
import OPFgen

def writeFile(filename,open_type,write_content):
  action = open(filename,open_type)
  action.write(write_content)
  action.close()
  
def randomString(count):
  basestring = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
  return "".join(random.sample(basestring,count))
  
def makeDir(directory):
  if not os.path.isdir(directory):
    os.mkdir(directory)
  else:
    pass
    
def kindleGen(opf_file,mobi_file):
  param = " -c1 -verbose -o "
  command = "kindlegen " + opf_file + param + mobi_file
  os.system(command)
  
def mailSend(mail_from,mail_to,attachment):
  subject = attachment
  message = "BR/mobi book generated by mobi.pagebrin.com"
  if not len(mail_to) == 0:
    if mail_from:
      mail_from = " ".join(["-r",mail_from])
    command = " ".join(["echo",message,"|","mail","-s",subject,"-a",attachment,mail_from,mail_to])
    os.system(command)
  else:
    pass
  
def main():
  # read the config file.
  config_file = "config.cfg"
  config = ConfigParser()
  config.read(config_file)
  
  mail_from    = config.get("SYSTEM","mail from")
  mail_to      = config.get("SYSTEM","mail to")
  base_dir     = config.get("SYSTEM","base directory")
  mobi_dir     = config.get("SYSTEM","mobi directory")
  publ_dir     = config.get("SYSTEM","publish directory")
  config_file  = os.path.join(base_dir,"config.cfg")
  
  makeDir(mobi_dir)
  
  config_list = config.sections()
  rss_list    = [i for i in config_list if re.search(r"RSS",i)]
  for item in rss_list:
    title        = config.get(item,"title")
    creator      = config.get(item,"creator")
    publisher    = config.get(item,"publisher")
    source       = config.get(item,"source")
    rights       = config.get(item,"rights")
    subject      = config.get(item,"subject")
    description  = config.get(item,"description")
    contributor  = config.get(item,"contributor")
    type2        = config.get(item,"type2")
    format2      = config.get(item,"format2")
    identifier   = config.get(item,"identifier")
    language     = config.get(item,"language")
    relation     = config.get(item,"relation")
    coverage     = config.get(item,"coverage")

    url                = config.get(item,"rss_url")
    findall_key        = config.get(item,"findall key")
    find_key           = config.get(item,"find key")
    pageparse_keyword  = config.get(item,"pageparse keyword")
    handle_weekday     = config.get(item,"handle weekday")

    date      = time.strftime("%Y-%m-%d", time.localtime())
    date_week = time.strftime("%Y%W", time.localtime())
    find_key  = find_key.split(",")
    bookid    = randomString(12)
    
    title2   = title + "-" + date_week

    # generate the url of this week's nfpeople
    if re.search(r'nfpeople',title):
      uri = str(int(time.strftime("%W", time.localtime())) + 7)
      uri = "Magazine-detail-item-" + uri + ".html"
      url += uri
    
    collection = "rss_" + title
    # RSS parse and write into database.
    content = RSSparse.fetchHtml(url)
    if re.search(r'nfpeople',url):
      list_today = RSSparse.fetchListNFpeople(content)
    else:
      list_today = RSSparse.fetchList(content,findall_key,find_key)
    for i in list_today:
      RSSparse.insertDB(collection,i)
    
    weekday = time.strftime("%w", time.localtime())
    if weekday != handle_weekday:
      continue
    else:
      pass
    
    # PAGE parse
    list_index = RSSparse.queryDB(collection)
    # if list_index is blank, skip it.
    if not list_index:
      continue

    # create directory for temp file. 
    temp_dir = os.path.join(config.get("SYSTEM","temp directory"),str(int(time.time())))
    makeDir(temp_dir)
    os.chdir(temp_dir)
      
    # down html file and image.
    index = 1
    list_temp = list_index[:]
    for i in list_index:
      print i['link']
      html_content = RSSparse.fetchHtml(i['link'])
      if not html_content:
        RSSparse.errorDB1(collection,i['link'])
        list_temp.remove(i)
        continue
      if re.search(r'nfpeople',title):
        page = PAGEparse.pageFormatNFpeople(page)
      else:
        page = PAGEparse.pageFormat(html_content,pageparse_keyword)
      if not page:
        RSSparse.errorDB2(collection,i['link'])
        list_temp.remove(i)
        continue
      page_downloadimg = PAGEparse.downloadIMG(page,title)
      page_addbodytag = PAGEparse.addBodytag(page_downloadimg)
      page_entire = PAGEparse.htmlHeader() + page_addbodytag
      out_filename = str(index) + ".html"
      #out_filename = temp_dir + out_filename
      PAGEparse.writeHtml(out_filename,page_entire)
      index += 1
      # update database's is_operate name.
      RSSparse.updateDB(collection,i['link'])
    list_index = list_temp[:]

    # OPF generation
    opf_metadata = OPFgen.opfMetadata(item,config_file)
    opf_entire = OPFgen.opfHeader(bookid) + opf_metadata + OPFgen.opfMainfest(list_index) + OPFgen.opfSpine(list_index) + OPFgen.opfGuide() + OPFgen.opfFooter()
    opf_filename = "index.opf"
    writeFile(opf_filename,"w",opf_entire)

    # INDEX html file generation
    html_header = OPFgen.htmlHeader()
    html_body = OPFgen.htmlBody(list_index)
    html_body = OPFgen.addBodytag(html_body)
    index_entire = html_header + html_body
    html_filename = "0.html"
    writeFile(html_filename,"w",index_entire)

    # KUG.ncx generation
    ncx_header = OPFgen.ncxHeader()
    ncx_head = OPFgen.ncxHead(bookid)
    ncx_doctitle = OPFgen.ncxDocTitle(title2)
    ncx_docauthor = OPFgen.ncxDocAuthor(creator)
    ncx_entirenavpoint = OPFgen.ncxEntireNavPoint(list_index)
    ncx_navmap = OPFgen.ncxNavMap(ncx_entirenavpoint)
    ncx_body = ncx_head + ncx_doctitle + ncx_docauthor + ncx_navmap
    ncx_body = OPFgen.ncxBody(ncx_body)
    ncx_entire = ncx_header + ncx_body
    ncx_filename = "KUG.ncx"
    writeFile(ncx_filename,"w",ncx_entire)
    
    # genaration the .mobi file use system tool kindlegen
    opf_file = "index.opf"
    mobi_file = title2 + ".mobi"
    if os.path.isfile(os.path.join(mobi_dir,mobi_file)):
      mobi_file = title2 + "-" + randomString(6) + ".mobi"
    kindleGen(opf_file,mobi_file)
    if publ_dir:
      shutil.copy(mobi_file,publ_dir)
    shutil.move(mobi_file,mobi_dir)
    
    # mail mobi book as attachment to specified mail address.
    os_type = platform.system() 
    if os_type == "Linux":
      os.chdir(mobi_dir)
      mailSend(mail_from,mail_to,mobi_file)

if __name__ == "__main__":
  main()
